spring:
  main:  
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientId>
            client-secret: <clientSecret>
 
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: CREATE_IF_NOT_EXISTS
      request:
        timeout: 30s
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s 

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: fe404251-e54e-4f24-b6e7-c9adb3267a2e-1 
    region: us-east1
    keyspace: main
    application.token: <token>